INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'CFF 35','Dometic',649,'Questo versatile modello, che si aggiunge alla gamma di dispense portatili Dometic, presenta un design elegante: coperchio a doppia cerniera ed efficiente disposizione dello spazio interno, ideale per l’outdoor. Lo spesso isolamento della CFF 35 garantisce un eccellente raffreddamento.','dometic_cff35.png',100,'frigorifero');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'BordBar AS 25','Dometic',119,'Frigorifero portatile termoelettrico per auto, 20 l. Mantiene freschi cibi e bevande durante il viaggio. Un frigorifero portatile termoelettrico per auto a prezzo accessibile.','dometic_as25.png',100,'frigorifero');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'CoolFun CK 40D','Dometic',399,'Frigo/freezer portatile ibrido, 38 l. Essendo multifunzione, questo frigorifero portatile ibrido è particolarmente efficiente e ad alte prestazioni.','dometic_b40d.png',10,'frigorifero');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'Roma Chair Ore','Dometic',85,'Sedia reclinabile. La gamma di sedie Roma è realizzata in PVC textilene, il che le rende impermeabili, comode e funzionali. Reclinabile in 7 posizioni, la sedia Lusso Roma è ideale da utilizzare a tavola o nei momenti di relax.','dometic_roma.png',10,'sedia');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'Milano Redux','Dometic',132.50,'Sedia reclinabile. La struttura in filato di bottiglia di plastica riciclata rende questa sedia estremamente comoda, funzionale e facile da pulire. Reclinabile in 7 posizioni, la sedia Lusso Milano Redux è ideale da utilizzare a tavola o nei momenti di relax.','dometic_milano.png',10,'sedia');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'Tub 180 Ore','Dometic',80,'Sedia da campeggio pieghevole. La classica sedia Tub è riprogettata per una maggiore resistenza e durevolezza.','dometic_chair180.png',100,'sedia');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'Leaf Side Table','Dometic',45,'Tavolo da campeggio. Robusto e leggero, il tavolino laterale Leaf si monta velocemente. Ideale per 1-2 persone. ','dometic_leaf.png',100,'tavolo');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'Element Table Medium','Dometic',95,'Tavolo da campeggio. Riunite la famiglia e gli amici intorno a questo tavolo medio. Con leggero telaio in alluminio, piano impermeabile e gambe regolabili.','dometic_element.png',100,'tavolo');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'Zero Light Oak','Dometic',200,'Tavolo da campeggio, leggero e pieghevole. Tavolo ripiegabile grande, ultra-leggero. Vanta un nuovo sistema di apertura one-touch, telaio leggero in alluminio e piano in rovere chiaro.','dometic_zero.png',1,'tavolo');

INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'ECOVIP CAMPERVAN','Laika',54000,'La maestria artigianale italiana incanta per l’estetica e convince per la tecnica. La serie Ecovip è parte integrante della gamma Laika dal 1992 e continuerà a ispirare per decenni famiglie intere di viaggiatori con un’eccellente tecnologia e un’inimitabile combinazione di bellezza, comfort e spirito d’avventura.','Laika_Ecovip_CamperVan.png',10,'furgonato');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'KOSMO MANSARDATO','Laika',60000,'Eleganza accogliente e struttura spaziosa. Grazie alla sua zona notte integrata, Kosmo Mansardato offre spazio a sufficienza per tutta la famiglia: per una vacanza nel segno della comodità.','Kosmo-Mansardato.png',10,'mansardato');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'KREOS PROFILATO','Laika',75000,'La serie Kreos coniuga lusso, tecnologia e versatilità. Un’autentica combinazione di stile, comfort di guida e raffinato design italiano: nel Kreos, l’eleganza non conosce confini e viaggiare in camper diventa un sogno ad occhi aperti.','Laika-Kreos-Low_Profile.png',1,'profilato');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'ECOVIP MOTORHOME','Laika',95000,'Oltre all’impareggiabile design interno ed esterno, peculiarità della gamma Ecovip Motorhome è il perfetto isolamento, sinonimo di temperature ideali e massimo comfort tutto l’anno.','Ecovip-Motorhome.png',1,'motorhome');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'BOXDRIVE XL','Knaus',73000,'Un miracolo dal punto di vista tecnologico ed in termini di spazio, pronto ad affrontare qualsiasi avventura, grazie alla sua dinamica di guida su telaio MAN TGE e ad una lunghezza inferiore ai 6 metri. Non importa se siete in viaggio con i familiari o con gli amici, grazie al letto nel tetto rialzato, le due zone notte sono separate per garantire il massimo comfort per 4 persone.','knaus-boxdrive-xl.png',10,'furgonato');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'L!VE TI','Knaus',64800,'Percepire la libertà, godersi la vita, scoprire il mondo! Con il L!VE TI nuovo di zecca l’approccio al mondo del camping KNAUS diventa così facile come mai prima d’ora. Scegliere una delle 4 piante e le numerose opzioni – e adattare il proprio L!VE TI esclusivamente alle proprie esigenze. Sia per un lungo viaggio o solo per una escursione nel fine settimana: con il L!VE TI si vive il design dinamico, la qualità di prima classe e il rapporto prezzo/prestazioni unico nel suo genere, che crea nuovi standard. ','knaus-liveti.png',10,'profilato');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'SUN I','Knaus',130000,'Il nostro liner di lusso si presenta in perfetta forma fin nei minimi dettagli. Percorrendo lunghi tratti sulle autostrade del nord o tortuose strade di campagna nei paesi mediterranei, con la sua maschera anteriore e gli esterni dinamici il SUN I colpisce per l’aspetto lussuoso e l’eleganza sportiva. Il SUN I non convince solo per il suo aspetto imponente, ma anche per la particolarità dei suoi dettagli interni, come il doppio pavimento riscaldato in stile yacht o le pregiate finiture in pelle. Salite, e innamoratevi a prima vista.  ','knaus-suni.png',10,'motorhome');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'Twin Sport','Adria',64000,'I nostri modelli Twin Sports attireranno i più avventurosi, grazie ai posti letto aggiuntivi, al soggiorno e allo spazio di stivaggio. Realizzato sul nuovo Fiat Ducato, con tetto a soffietto dal design esclusivo e vano notte. Perfetto per gli sportivi con attrezzatura outdoor e anche per le famiglie con bambini.','adria_twin.png',10,'furgonato');
INSERT INTO PRODOTTO (idProdotto,nome,marca,prezzo,descrizione,img,qnt,tipo) VALUES (idProdotto,'Coral XL','Adria',75000,'La gamma Coral XL definisce il punto di riferimento per i camper mansardati eleganti e pratici. Linee eleganti e interni spaziosi e pratici fino a 6 posti omologati, che li rendono perfetti per famiglie numerose e gruppi di amici.','adria_coral_xl.png',10,'mansardato');